version: '3.8'
services:
  oracle-db:
    build: ./db
    ports:
      - "1521:1521"
    volumes:
      - oracle-data:/opt/oracle/oradata
    networks:
      - apex-network

  ords:
    build: ./ords
    depends_on:
      - oracle-db
    ports:
      - "8080:8080"
    networks:
      - apex-network

volumes:
  oracle-data:
networks:
  apex-network:
    driver: bridge
