version: "1"

services:
  db:
    image: apex-db
    ports:
      - "1521:1521"
    environment:
      - ORACLE_ALLOW_REMOTE=true
      - ORACLE_DISABLE_ASYNCH_IO=true
      - ORACLE_ENABLE_XDB=true
      - ORACLE_ENABLE_LTS=true
      - ORACLE_ENABLE_APEX=true
      - ORACLE_PASSWORD=oracle
      - ORACLE_SID=apex
      - ORACLE_SYSTEM_PASSWORD=oracle
      - ORACLE_USER_PASSWORD=oracle
    volumes:
      - ./apex:/opt/oracle/oradata
    networks:
      - apex-network
  ords:
      image: apex-ords
      ports:
        - "8080:8080"
      environment:
        - ORACLE_HOST=db
        - ORACLE_PORT=1521
        - ORACLE_SERVICE=apex
        - ORACLE_USER_PASSWORD=oracle
        - ORACLE_USER=apex_public_user
        - ORACLE_PASSWORD=oracle
        - APEX_PUBLIC_USER_PASSWORD=oracle
        - APEX_LISTENER_PASSWORD=oracle
        - APEX_REST_PASSWORD=oracle
        - APEX_IMAGES_PASSWORD=oracle
        - APEX_PASS=oracle
        - APEX_LISTENER_PASS=oracle
        - APEX_REST_PASS=oracle
        - APEX_IMAGES_PASS=oracle
        - APEX_PUBLIC_USER_PASS=oracle
      volumes:
        - ./apex:/opt/oracle/oradata
      networks:
        - apex-network

networks:
  apex-network:

volumes:
  apex: